### ISSUE TITLE
An error occurs when executing duplicates.

### ISSUE THREAD

**Issue by CatsMiaow** [octalmage/active-window#13]
#### Test Code
```javascript
setInterval(function() {
  monitor.getActiveWindow(callback);
}, 1000);
```

#### Error
![error](http://discord.tested.kr/20170102_213612.png)

#### Cause
```javascript
// active-window/index.js
parameters = config.parameters;
parameters.push(repeats);
parameters.push(interval);
console.log(parameters); // overwrite configs...
```

#### Fixed
```javascript
const parameters = config.parameters.slice();
parameters.push(repeats);
parameters.push(interval);
```
![error](http://discord.tested.kr/20170102_213706.png)

End.

**Comment by tallpants** [comment]
I came here looking for this issue as well. Since you already have the fix could you submit a PR and maybe the author will accept it?

**Comment by robsonvn** [comment]
It was my bad and I totally agree with this solution. 
It would be better if you submit a PR as @adithyakreddy said and then @octalmage could accept it.

**Comment by tallpants** [comment]
I submitted a PR with the fix that @CatsMiaow described [here](https://github.com/octalmage/active-window/pull/14), let's hope @octalmage accepts it.
